services:
  bot:
    container_name: modmail
    image: seliba/modmail-bot:latest
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
      - ./logs/:/app/logs/
    networks:
      - database
      
  db:
    container_name: modmail_db
    image: postgres:17.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=modmail
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=modmail
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - database
    expose:
      - 5432
      
networks:
    database:
        external: false
        name: modmail_db
